{
    "openapi": "3.0.2",
    "info": {
        "title": "Giveback Ninja",
        "version": "1.0.0",
        "license": {
            "name": "MIT License",
            "url": "https://opensource.org/licenses/MIT"
        }
    },
    "paths": {
        "/user": {
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {

                        }
                    },
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/User"
                                }
                            }
                        },
                        "description": "Creates a user within the system."
                    }
                },
                "summary": "Registers a new user in the system."
            }
        },
        "/scorecards": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/UserScorecard"
                                    }
                                }
                            }
                        },
                        "description": "Returns a list of all user scorecards."
                    }
                },
                "summary": "Get all user scorecards."
            }
        },
        "/scorecards/{id}": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UserScorecard"
                                },
                                "examples": {
                                    "super_ninja": {
                                        "value": {
                                            "id": 1,
                                            "username": "super_ninja",
                                            "total": 248,
                                            "beltColor": "black",
                                            "pointsToNextLevel": 0,
                                            "githubReviewedPullRequests": 24,
                                            "githubClosedIssues": 0,
                                            "servicesSupportMergeRequests": 0,
                                            "servicesSupportClosedIssues": 0,
                                            "servicesSupportReviewedMergeRequests": 0,
                                            "githubPullRequests": 34,
                                            "gitlabMergeRequests": 43,
                                            "trelloCardsClosed": 23,
                                            "thoughtLeadershipCardsClosed": 1,
                                            "servicesSupportCardsClosed": 10
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "summary": "Get UserScorecard info for a specific user."
            },
            "parameters": [
                {
                    "name": "id",
                    "description": "The unique identifier of a specific user.",
                    "schema": {
                        "type": "integer"
                    },
                    "in": "path",
                    "required": true
                }
            ]
        }
    },
    "components": {
        "schemas": {
            "User": {
                "title": "Root Type for User",
                "description": "",
                "type": "object",
                "properties": {
                    "displayName": {
                        "description": "The name displayed to all users of the system. Typically the users first and last name.",
                        "type": "string"
                    },
                    "username": {
                        "description": "The user's Red Hat Kerberos ID.",
                        "type": "string"
                    },
                    "githubUsername": {
                        "description": "The user's Github username.",
                        "type": "string"
                    },
                    "trelloUsername": {
                        "description": "The user's Trello username.",
                        "type": "string"
                    },
                    "email": {
                        "description": "The Red Hat email associated with the user.",
                        "type": "string"
                    }
                },
                "example": {
                    "displayName": "Super Ninja",
                    "username": "super_ninja",
                    "githubUsername": "super_ninja",
                    "trelloUsername": "super_ninja",
                    "email": "super_ninja@redhat.com"
                }
            },
            "UserScorecard": {
                "title": "Root Type for UserScorecard",
                "description": "All stats around a user that are used to calculate Ninja Belt level.",
                "required": [
                    "id",
                    "username",
                    "pointsToNextLevel",
                    "beltColor"
                ],
                "type": "object",
                "properties": {
                    "username": {
                        "description": "Kerberos ID.",
                        "type": "string"
                    },
                    "total": {
                        "type": "integer"
                    },
                    "beltColor": {
                        "description": "The current belt level (color) of the user.",
                        "type": "string"
                    },
                    "pointsToNextLevel": {
                        "description": "The amount of points the user needs to reach the next belt level.",
                        "type": "integer"
                    },
                    "githubReviewedPullRequests": {
                        "description": "The amount of GitHub pull requests the user has reviewed.",
                        "type": "integer"
                    },
                    "githubClosedIssues": {
                        "description": "The amount of GitHub issues the user has closed.",
                        "type": "integer"
                    },
                    "servicesSupportMergeRequests": {
                        "description": "The amount of Services Support merge requests the user has submitted.",
                        "type": "integer"
                    },
                    "servicesSupportClosedIssues": {
                        "description": "The amount of Services Support issues the user has closed.",
                        "type": "integer"
                    },
                    "servicesSupportReviewedMergeRequests": {
                        "description": "The amount of Services Support merge requests the user has reviewed.",
                        "type": "integer"
                    },
                    "githubPullRequests": {
                        "description": "The amount of GitHub pull requests the user has submitted.",
                        "type": "integer"
                    },
                    "gitlabMergeRequests": {
                        "description": "The amount of GitLab merge requests the user has submitted.",
                        "type": "integer"
                    },
                    "trelloCardsClosed": {
                        "description": "The amount of Trello cards the user has closed.",
                        "type": "integer"
                    },
                    "thoughtLeadershipCardsClosed": {
                        "description": "The amount of Thought Leadership cards the user has closed.",
                        "type": "integer"
                    },
                    "servicesSupportCardsClosed": {
                        "description": "The amount of Services Support cards the user has closed.",
                        "type": "integer"
                    },
                    "id": {
                        "description": "Unique, numeric identifier of a UserScorecard resource.",
                        "type": "integer"
                    }
                },
                "example": {
                    "username": "super_ninja",
                    "total": 248,
                    "beltColor": "black",
                    "pointsToNextLevel": 0,
                    "githubReviewedPullRequests": 24,
                    "githubClosedIssues": 0,
                    "servicesSupportMergeRequests": 0,
                    "servicesSupportClosedIssues": 0,
                    "servicesSupportReviewedMergeRequests": 0,
                    "githubPullRequests": 34,
                    "gitlabMergeRequests": 43,
                    "trelloCardsClosed": 23,
                    "thoughtLeadershipCardsClosed": 1,
                    "servicesSupportCardsClosed": 10
                }
            }
        }
    }
}